name: release

on:
  workflow_dispatch:

jobs:

  sdist:
    name: Package source
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          architecture: x64

      - name: deps
        run: python -m pip install -U pip wheel setuptools ccompiler

      - name: build
        run: python build.py

      - name: sdist
        run: python setup.py sdist

      - name: wheel
        run: python setup.py bdist_wheel

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist/*
